### ISSUE TITLE
FileNotFoundError and Directory Nonexistent Errors When Running Example Dataset

### ISSUE THREAD

**Issue by CaroleBelliardo** [kangxiongbin/HyLight#2]
Hi Kangxiongbin,

Thank you for developing this impressive software. Utilizing both short and long reads for metagenomic assembly is a fantastic approach! However, I encountered some issues while using HyLight on our data as well as the provided "example" dataset. Both attempts resulted in the same error message. After following the manual installation instructions and running the tool on the "example" dataset, I encountered multiple errors related to missing files and directories, culminating in a FileNotFoundError. Below are the details of the errors and the setup.

## Here, the Singularity source code for install HyLight :
```
BootStrap: library
From: ubuntu:18.04

%help
Hybrid assembly of SR & LR

%setup
mkdir ${SINGULARITY_ROOTFS}/home/tools

%files
Miniconda3-latest-Linux-x86_64.sh /home/tools/.
HyLight /home/tools/.

%post
apt-get -y update
apt-get -y install wget build-essential
apt-get -y install g++
apt-get -y install make
apt-get -y install bash
apt-get install -y locales 
apt-get -y install nano
apt-get -y install less
locale-gen en_US.UTF-8

cd /home/tools/

yes y | bash ./Miniconda3-latest-Linux-x86_64.sh -b -p /home/tools/miniconda

export PATH="$PATH:/home/tools/miniconda/bin/"

conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
conda install -y python=3.8 scipy pandas minimap2 bfc fmlrc2 ropebwt2 miniasm

%labels
Maintainer Carole Belliardo
Updater  Carole Belliardo<carole.belliardo@inra.fr>

ContainerVersion v1
Software

%environment
    export LC_ALL=en_US.utf8
    export PATH=/home/tools/miniconda/bin:$PATH
    export LANGUAGE=en_US.UTF-8
    export LANG=en_US.UTF-8

%runscript

```
## Slurm script for running HiLight on example dataset : 
```
#!/bin/bash

#Submit this script with: sbatch thefilename

#SBATCH --ntasks=1   # number of processor cores (i.e. tasks)
#SBATCH --cpus-per-task=20     # number of CPU per task #4
#SBATCH --nodes=1   # number of nodes
#SBATCH --mem=120G   # memory per Nodes   #38
#SBATCH -J "HyLight"   # job name
#SBATCH --mail-type=ALL
#SBATCH -e slurm-HyLight-%j.err
#SBATCH -o slurm-HyLight-%j.out
#SBATCH -p all

module load singularity/3.5.3
SING2='singularity exec --bind /kwak/hub'
SING_IMG='/kwak/hub/25_cbelliardo/MISTIC/singularity/HyLight.sif'

lr='/home/tools/HyLight/example/long_reads.fq'
sr='/home/tools/HyLight/example/short_reads.fq'

script='/home/tools/HyLight/script/HyLight.py'
$SING2 $SING_IMG python $script -l $lr -s $sr  -t $SLURM_JOB_CPUS_PER_NODE --min_ovlp_len 1000 -o "salade_I__test_v2"

```
# Error message is : 
```[2024-08-07T08:02:36Z INFO  fmlrc::bv_bwt] Building 8-mer cache...
[2024-08-07T08:02:36Z INFO  fmlrc::bv_bwt] Finished BWT initialization.
[2024-08-07T08:02:36Z INFO  fmlrc2] Starting read correction processes...
[2024-08-07T08:02:42Z INFO  fmlrc2] Finished processing 2412 total reads in range [0, 18446744073709551615)
2024-08-07 09:02:42,456 - /home/tools/HyLight/script/HyLight.py[line:114] - INFO: generate overlap information among long reads
2024-08-07 09:02:43,234 - /home/tools/HyLight/script/HyLight.py[line:122] - INFO: computing all-vs-all long read overlaps and then filter wrong overlap by SNPs and sort overlap by overlap score.
split: cannot open 'salade_I__test_v2/1.split_fastx/s1.fa' for reading: No such file or directory
sh: 1: cannot create salade_I__test_v2/2.overlap/s1_s1.paf: Directory nonexistent
rm: cannot remove 'sub925*': No such file or directory
2024-08-07 09:02:43,319 - /home/tools/HyLight/script/HyLight.py[line:132] - INFO: assemble long reads with clean graph
sh: 1: cannot create salade_I__test_v2/tmp//contigs1.gfa: Directory nonexistent
Traceback (most recent call last):
  File "/home/tools/HyLight/script/HyLight.py", line 381, in <module>
    sys.exit(main())
  File "/home/tools/HyLight/script/HyLight.py", line 142, in main
    gfa2fa(gfa, long_con)
  File "/home/tools/HyLight/script/HyLight.py", line 330, in gfa2fa
    with open(gfa, 'r') as gfa_file, open(fa, 'w') as output_file:
FileNotFoundError: [Errno 2] No such file or directory: 'salade_I__test_v2/tmp//contigs1.gfa'
 ```

The log file contains: 
 ```
2024-08-07 00:48:07,241 - /home/tools/HyLight/script/HyLight.py[line:100] - INFO: correcting long reads with short reads
2024-08-07 01:31:10,225 - /home/tools/HyLight/script/HyLight.py[line:114] - INFO: generate overlap information among long reads
2024-08-07 01:35:38,301 - /home/tools/HyLight/script/HyLight.py[line:122] - INFO: computing all-vs-all long read overlaps and then filter wrong overlap by SNPs and sort overlap by overlap score.
2024-08-07 01:35:45,015 - /home/tools/HyLight/script/HyLight.py[line:132] - INFO: assemble long reads with clean graph
2024-08-07 09:02:08,385 - /home/tools/HyLight/script/HyLight.py[line:100] - INFO: correcting long reads with short reads
2024-08-07 09:02:42,456 - /home/tools/HyLight/script/HyLight.py[line:114] - INFO: generate overlap information among long reads
2024-08-07 09:02:43,234 - /home/tools/HyLight/script/HyLight.py[line:122] - INFO: computing all-vs-all long read overlaps and then filter wrong overlap by SNPs and sort overlap by overlap score.
2024-08-07 09:02:43,319 - /home/tools/HyLight/script/HyLight.py[line:132] - INFO: assemble long reads with clean graph
 ```

Thank you so much for your help in resolving this issue, I am available for more information about the run. 
Best regards,
Carole

**Comment by kangxiongbin** [comment]
We're delighted that you're using our software. Since my collaborator developed the Singularity and dock versions, I'm having him look into the issue. He'll get back to you in a day or two.

**Comment by kangxiongbin** [comment]
Or could you try installing it according to the following steps? If you encounter any issues, please let me know, and I'll be happy to help directly. Thank you very much! 

conda create -n HyLight
conda activate HyLight
conda install -c bioconda python=3.6 scipy pandas minimap2 bfc fmlrc2 ropebwt2 racon
git clone https://github.com/kangxiongbin/HyLight.git
cd HyLight
sh install.sh

**Comment by CaroleBelliardo** [comment]
Thanks for your answer. I'm sorry, but I forgot to tell you that the same error message occurs when I run the same command line on a classic laptop machine (without singularity) following your instructions always with your example dataset. Also, I would be interested in skipping all the previous steps and giving long reads and short reads as input for your tool. It could be a real improvement that allows us to easily and quickly use your software's last analysis of our data for a paper in the ongoing writing process. 
Thanks a lot. Have a nice day.

**Comment by kangxiongbin** [comment]
Hi CaroleBelliardo,

I found the issue. The output folder you provided isn't a full path. Try specifying the full path, like /work/bin/HyLight/example/, instead of just the name of the output folder.

I hope you can get Hylight running smoothly. If you have any other questions, feel free to reach out. Have a nice day!

Best,
Xiongbin

**Comment by CaroleBelliardo** [comment]
Thanks a lot for your help. We are interested in skipping the first step and directly providing contigs assembled independently from long-read and short-read as input to your software. Is there an option for this?

**Comment by CaroleBelliardo** [comment]
Also, I need help understanding how to use the option "_nsplit_". Could you provide more explanation and advice on data with 20Go of long-reads and 200Go of short-reads? Thank you a lot

**Comment by kangxiongbin** [comment]
1. When you process data, you can add "--corrected" this parameter and Hylight will skip the first step.
2. This depends on the performance of your server. You can set nsplit to 1000 or higher to prevent slow processing due to large data volumes. If your data exceeds 10GB, Hylight might take two weeks or even longer to complete. Improving Hylight's speed is something we plan to work on next.

**Comment by CaroleBelliardo** [comment]
Hi, thank you for your help. Providing a full path fixed the issues for the first steps, but another error message appeared after the 'assemble long reads with clean graph' step: 
```2024-08-11 10:08:43,041 - /home/tools/HyLight/script/HyLight.py[line:100] - INFO: correcting long reads with short reads
[2024-08-11T09:08:43Z INFO  fmlrc2_convert] Input parameters (required):
[2024-08-11T09:08:43Z INFO  fmlrc2_convert] 	Input BWT: "stdin"
[2024-08-11T09:08:43Z INFO  fmlrc2_convert] 	Output BWT: "/kwak/hub/25_cbelliardo/MISTIC/1_reads_rawdata/hybrid_assembly/salade_I__test_v3/tmp//comp_msbwt.npy"
[M::main_ropebwt2] inserted 50606576 symbols in 6.834 sec, 18.615 CPU sec
[M::main_ropebwt2] constructed FM-index in 8.485 sec, 19.040 CPU sec
[M::main_ropebwt2] symbol counts: ($, A, C, G, T, N) = (201622, 12056378, 13146208, 13154111, 23199, 12025058)
[M::main] Version: r187
[M::main] CMD: /home/tools/miniconda/bin/ropebwt2 -LR
[M::main] Real time: 11.146 sec; CPU: 20.785 sec
[2024-08-11T09:08:54Z INFO  fmlrc::bwt_converter] Converted BWT with symbol counts: [201622, 12056378, 13146208, 13154111, 23199, 12025058]
[2024-08-11T09:08:54Z INFO  fmlrc::bwt_converter] RLE-BWT byte length: 9031781
[2024-08-11T09:08:54Z INFO  fmlrc2_convert] RLE-BWT conversion complete.
[2024-08-11T09:08:54Z INFO  fmlrc2] Input parameters (required):
[2024-08-11T09:08:54Z INFO  fmlrc2] 	BWT: "comp_msbwt.npy"
[2024-08-11T09:08:54Z INFO  fmlrc2] 	Input reads: "/home/tools/HyLight/example/long_reads.fq"
[2024-08-11T09:08:54Z INFO  fmlrc2] 	Output corrected reads: "fmlrc1.fasta"
[2024-08-11T09:08:54Z INFO  fmlrc2] Execution Parameters:
[2024-08-11T09:08:54Z INFO  fmlrc2] 	verbose: false
[2024-08-11T09:08:54Z INFO  fmlrc2] 	threads: 30
[2024-08-11T09:08:54Z INFO  fmlrc2] 	cache size: 8
[2024-08-11T09:08:54Z INFO  fmlrc2] Correction Parameters:
[2024-08-11T09:08:54Z INFO  fmlrc2] 	reads to correct: [0, 18446744073709551615)
[2024-08-11T09:08:54Z INFO  fmlrc2] 	k-mer sizes: [21, 59]
[2024-08-11T09:08:54Z INFO  fmlrc2] 	abs. mininimum count: 2
[2024-08-11T09:08:54Z INFO  fmlrc2] 	dyn. minimimum fraction: 0.1
[2024-08-11T09:08:54Z INFO  fmlrc2] 	branching factor: 4
[2024-08-11T09:08:54Z INFO  fmlrc::bv_bwt] Loading BWT with 9031781 compressed values
[2024-08-11T09:08:54Z INFO  fmlrc::bv_bwt] Loaded BWT with symbol counts: [201622, 12056378, 13146208, 13154111, 23199, 12025058]
[2024-08-11T09:08:54Z INFO  fmlrc::bv_bwt] Allocating binary vectors...
[2024-08-11T09:08:54Z INFO  fmlrc::bv_bwt] Calculating binary vectors...
[2024-08-11T09:08:54Z INFO  fmlrc::bv_bwt] Constructing FM-indices...
[2024-08-11T09:08:54Z INFO  fmlrc::bv_bwt] Building 8-mer cache...
[2024-08-11T09:08:54Z INFO  fmlrc::bv_bwt] Finished BWT initialization.
[2024-08-11T09:08:55Z INFO  fmlrc2] Starting read correction processes...
[2024-08-11T09:09:04Z INFO  fmlrc2] Finished processing 2412 total reads in range [0, 18446744073709551615)
[2024-08-11T09:09:04Z INFO  fmlrc2] Input parameters (required):
[2024-08-11T09:09:04Z INFO  fmlrc2] 	BWT: "comp_msbwt.npy"
[2024-08-11T09:09:04Z INFO  fmlrc2] 	Input reads: "fmlrc1.fasta"
[2024-08-11T09:09:04Z INFO  fmlrc2] 	Output corrected reads: "fmlrc2.fasta"
[2024-08-11T09:09:04Z INFO  fmlrc2] Execution Parameters:
[2024-08-11T09:09:04Z INFO  fmlrc2] 	verbose: false
[2024-08-11T09:09:04Z INFO  fmlrc2] 	threads: 30
[2024-08-11T09:09:04Z INFO  fmlrc2] 	cache size: 8
[2024-08-11T09:09:04Z INFO  fmlrc2] Correction Parameters:
[2024-08-11T09:09:04Z INFO  fmlrc2] 	reads to correct: [0, 18446744073709551615)
[2024-08-11T09:09:04Z INFO  fmlrc2] 	k-mer sizes: [21, 59]
[2024-08-11T09:09:04Z INFO  fmlrc2] 	abs. mininimum count: 2
[2024-08-11T09:09:04Z INFO  fmlrc2] 	dyn. minimimum fraction: 0.1
[2024-08-11T09:09:04Z INFO  fmlrc2] 	branching factor: 4
[2024-08-11T09:09:04Z INFO  fmlrc::bv_bwt] Loading BWT with 9031781 compressed values
[2024-08-11T09:09:04Z INFO  fmlrc::bv_bwt] Loaded BWT with symbol counts: [201622, 12056378, 13146208, 13154111, 23199, 12025058]
[2024-08-11T09:09:04Z INFO  fmlrc::bv_bwt] Allocating binary vectors...
[2024-08-11T09:09:04Z INFO  fmlrc::bv_bwt] Calculating binary vectors...
[2024-08-11T09:09:05Z INFO  fmlrc::bv_bwt] Constructing FM-indices...
[2024-08-11T09:09:05Z INFO  fmlrc::bv_bwt] Building 8-mer cache...
[2024-08-11T09:09:05Z INFO  fmlrc::bv_bwt] Finished BWT initialization.
[2024-08-11T09:09:05Z INFO  fmlrc2] Starting read correction processes...
[2024-08-11T09:09:11Z INFO  fmlrc2] Finished processing 2412 total reads in range [0, 18446744073709551615)
[2024-08-11T09:09:11Z INFO  fmlrc2] Input parameters (required):
[2024-08-11T09:09:11Z INFO  fmlrc2] 	BWT: "comp_msbwt.npy"
[2024-08-11T09:09:11Z INFO  fmlrc2] 	Input reads: "fmlrc2.fasta"
[2024-08-11T09:09:11Z INFO  fmlrc2] 	Output corrected reads: "fmlrc3.fasta"
[2024-08-11T09:09:11Z INFO  fmlrc2] Execution Parameters:
[2024-08-11T09:09:11Z INFO  fmlrc2] 	verbose: false
[2024-08-11T09:09:11Z INFO  fmlrc2] 	threads: 30
[2024-08-11T09:09:11Z INFO  fmlrc2] 	cache size: 8
[2024-08-11T09:09:11Z INFO  fmlrc2] Correction Parameters:
[2024-08-11T09:09:11Z INFO  fmlrc2] 	reads to correct: [0, 18446744073709551615)
[2024-08-11T09:09:11Z INFO  fmlrc2] 	k-mer sizes: [21, 59]
[2024-08-11T09:09:11Z INFO  fmlrc2] 	abs. mininimum count: 2
[2024-08-11T09:09:11Z INFO  fmlrc2] 	dyn. minimimum fraction: 0.1
[2024-08-11T09:09:11Z INFO  fmlrc2] 	branching factor: 4
[2024-08-11T09:09:11Z INFO  fmlrc::bv_bwt] Loading BWT with 9031781 compressed values
[2024-08-11T09:09:11Z INFO  fmlrc::bv_bwt] Loaded BWT with symbol counts: [201622, 12056378, 13146208, 13154111, 23199, 12025058]
[2024-08-11T09:09:11Z INFO  fmlrc::bv_bwt] Allocating binary vectors...
[2024-08-11T09:09:11Z INFO  fmlrc::bv_bwt] Calculating binary vectors...
[2024-08-11T09:09:11Z INFO  fmlrc::bv_bwt] Constructing FM-indices...
[2024-08-11T09:09:11Z INFO  fmlrc::bv_bwt] Building 8-mer cache...
[2024-08-11T09:09:11Z INFO  fmlrc::bv_bwt] Finished BWT initialization.
[2024-08-11T09:09:11Z INFO  fmlrc2] Starting read correction processes...
[2024-08-11T09:09:17Z INFO  fmlrc2] Finished processing 2412 total reads in range [0, 18446744073709551615)
2024-08-11 10:09:17,809 - /home/tools/HyLight/script/HyLight.py[line:114] - INFO: generate overlap information among long reads
2024-08-11 10:09:18,597 - /home/tools/HyLight/script/HyLight.py[line:122] - INFO: computing all-vs-all long read overlaps and then filter wrong overlap by SNPs and sort overlap by overlap score.
2024-08-11 10:09:36,943 - /home/tools/HyLight/script/HyLight.py[line:132] - INFO: assemble long reads with clean graph
[M::main] ===> Step 1: reading read mappings <===
[M::ma_hit_read::0.009*1.40] read 3881 hits; stored 7762 hits and 1723 sequences (20628149 bp)
[M::main] ===> Step 2: 1-pass (crude) read selection <===
[M::ma_hit_sub::0.010*1.35] 1723 query sequences remain after sub
[M::ma_hit_cut::0.010*1.35] 7704 hits remain after cut
[M::ma_hit_flt::0.010*1.34] 7704 hits remain after filtering; crude coverage after filtering: 2.67
[M::main] ===> Step 3: 2-pass (fine) read selection <===
[M::ma_hit_sub::0.010*1.32] 1717 query sequences remain after sub
[M::ma_hit_cut::0.011*1.32] 7704 hits remain after cut
[M::ma_hit_contained::0.011*1.30] 578 sequences and 1360 hits remain after containment removal
[M::main] ===> Step 4: graph cleaning <===
[M::ma_sg_gen] read 1360 arcs
[M::main] ===> Step 4.1: transitive reduction <===
[M::asg_arc_del_trans] transitively reduced 474 arcs
[M::asg_arc_del_multi] removed 0 multi-arcs
[M::asg_arc_del_asymm] removed 0 asymmetric arcs
[M::main] ===> Step 4.2: initial tip cutting and bubble popping <===
[M::asg_cut_tip] cut 39 tips
[M::asg_pop_bubble] popped 0 bubbles and trimmed 0 tips
[M::main] ===> Step 4.3: cutting short overlaps (1 rounds in total) <===
[M::asg_arc_del_short] removed 0 short overlaps
[M::main] ===> Step 4.4: removing short internal sequences and bi-loops <===
[M::asg_cut_internal] cut 0 internal sequences
[M::asg_cut_biloop] cut 0 small bi-loops
[M::asg_cut_tip] cut 0 tips
[M::asg_pop_bubble] popped 0 bubbles and trimmed 0 tips
[M::main] ===> Step 4.5: aggressively cutting short overlaps <===
[M::asg_arc_del_short] removed 0 short overlaps
[M::main] ===> Step 5: generating unitigs <===
[M::main] Version: 0.3-r179
[M::main] CMD: /home/tools/HyLight/tools/miniasm/miniasm -d 10000 -n 1 -e 1 -c 1 -f /kwak/hub/25_cbelliardo/MISTIC/1_reads_rawdata/hybrid_assembly/salade_I__test_v3/1.split_fastx/s1.fa /kwak/hub/25_cbelliardo/MISTIC/1_reads_rawdata/hybrid_assembly/salade_I__test_v3/2.overlap/s1_s1.paf
[M::main] Real time: 0.071 sec; CPU: 0.071 sec
2024-08-11 10:09:37,142 - /home/tools/HyLight/script/HyLight.py[line:144] - INFO: Start assemble short reads
2024-08-11 10:09:37,142 - /home/tools/HyLight/script/HyLight.py[line:146] - INFO: generate overlap between reads and temporary reference
sh: 1: racon: not found
[M::main] ===> Step 1: reading read mappings <===
[M::ma_hit_read::0.004*0.74] read 697 hits; stored 1188 hits and 321 sequences (2539191 bp)
[M::main] ===> Step 2: 1-pass (crude) read selection <===
[M::ma_hit_sub::0.004*0.75] 321 query sequences remain after sub
[M::ma_hit_cut::0.004*0.75] 1150 hits remain after cut
[M::ma_hit_flt::0.004*0.76] 1150 hits remain after filtering; crude coverage after filtering: 2.44
[M::main] ===> Step 3: 2-pass (fine) read selection <===
[M::ma_hit_sub::0.004*0.76] 318 query sequences remain after sub
[M::ma_hit_cut::0.004*0.76] 1150 hits remain after cut
[M::ma_hit_contained::0.004*0.77] 102 sequences and 162 hits remain after containment removal
[M::main] ===> Step 4: graph cleaning <===
[M::ma_sg_gen] read 162 arcs
[M::main] ===> Step 4.1: transitive reduction <===
[M::asg_arc_del_trans] transitively reduced 42 arcs
[M::asg_arc_del_multi] removed 0 multi-arcs
[M::asg_arc_del_asymm] removed 0 asymmetric arcs
[M::main] ===> Step 4.2: initial tip cutting and bubble popping <===
[M::asg_cut_tip] cut 17 tips
[M::asg_pop_bubble] popped 0 bubbles and trimmed 0 tips
[M::main] ===> Step 4.3: cutting short overlaps (1 rounds in total) <===
[M::asg_arc_del_short] removed 0 short overlaps
[M::main] ===> Step 4.4: removing short internal sequences and bi-loops <===
[M::asg_cut_internal] cut 0 internal sequences
[M::asg_cut_biloop] cut 0 small bi-loops
[M::asg_cut_tip] cut 0 tips
[M::asg_pop_bubble] popped 0 bubbles and trimmed 0 tips
[M::main] ===> Step 4.5: aggressively cutting short overlaps <===
[M::asg_arc_del_short] removed 0 short overlaps
[M::main] ===> Step 5: generating unitigs <===
[M::main] Version: 0.3-r179
[M::main] CMD: /home/tools/HyLight/tools/miniasm/miniasm -d 10000 -n 1 -e 1 -c 1 -f /kwak/hub/25_cbelliardo/MISTIC/1_reads_rawdata/hybrid_assembly/salade_I__test_v3/1.split_fastx/s1.fa /kwak/hub/25_cbelliardo/MISTIC/1_reads_rawdata/hybrid_assembly/salade_I__test_v3/tmp//ov_long_remain.paf
[M::main] Real time: 0.046 sec; CPU: 0.045 sec
sh: 1: racon: not found
[M::main] ===> Step 1: reading read mappings <===
[M::ma_hit_read::0.003*0.67] read 146 hits; stored 250 hits and 94 sequences (736377 bp)
[M::main] ===> Step 2: 1-pass (crude) read selection <===
[M::ma_hit_sub::0.003*0.68] 94 query sequences remain after sub
[M::ma_hit_cut::0.003*0.68] 244 hits remain after cut
[M::ma_hit_flt::0.003*0.69] 244 hits remain after filtering; crude coverage after filtering: 2.11
[M::main] ===> Step 3: 2-pass (fine) read selection <===
[M::ma_hit_sub::0.003*0.69] 93 query sequences remain after sub
[M::ma_hit_cut::0.003*0.69] 244 hits remain after cut
[M::ma_hit_contained::0.003*0.69] 16 sequences and 0 hits remain after containment removal
[M::main] ===> Step 4: graph cleaning <===
[M::ma_sg_gen] read 0 arcs
[M::main] ===> Step 4.1: transitive reduction <===
[M::asg_arc_del_trans] transitively reduced 0 arcs
[M::main] ===> Step 4.2: initial tip cutting and bubble popping <===
[M::asg_cut_tip] cut 16 tips
[M::asg_arc_del_multi] removed 0 multi-arcs
[M::asg_arc_del_asymm] removed 0 asymmetric arcs
[M::asg_pop_bubble] popped 0 bubbles and trimmed 0 tips
[M::main] ===> Step 4.3: cutting short overlaps (1 rounds in total) <===
[M::asg_arc_del_short] removed 0 short overlaps
[M::main] ===> Step 4.4: removing short internal sequences and bi-loops <===
[M::asg_cut_internal] cut 0 internal sequences
[M::asg_cut_biloop] cut 0 small bi-loops
[M::asg_cut_tip] cut 0 tips
[M::asg_pop_bubble] popped 0 bubbles and trimmed 0 tips
[M::main] ===> Step 4.5: aggressively cutting short overlaps <===
[M::asg_arc_del_short] removed 0 short overlaps
[M::main] ===> Step 5: generating unitigs <===
[M::main] Version: 0.3-r179
[M::main] CMD: /home/tools/HyLight/tools/miniasm/miniasm -d 10000 -n 1 -e 1 -c 1 -f /kwak/hub/25_cbelliardo/MISTIC/1_reads_rawdata/hybrid_assembly/salade_I__test_v3/1.split_fastx/s1.fa /kwak/hub/25_cbelliardo/MISTIC/1_reads_rawdata/hybrid_assembly/salade_I__test_v3/tmp//ov_long_remain.paf
[M::main] Real time: 0.044 sec; CPU: 0.041 sec
sort: cannot read: 'sub256*_sorted_overlap.paf': No such file or directory
rm: cannot remove 'sub256*': No such file or directory
sh: 1: racon: not found
 ```
 log file contain :  ```2024-08-07 00:48:07,241 - /home/tools/HyLight/script/HyLight.py[line:100] - INFO: correcting long reads with short reads
2024-08-07 01:31:10,225 - /home/tools/HyLight/script/HyLight.py[line:114] - INFO: generate overlap information among long reads
2024-08-07 01:35:38,301 - /home/tools/HyLight/script/HyLight.py[line:122] - INFO: computing all-vs-all long read overlaps and then filter wrong overlap by SNPs and sort overlap by overlap score.
2024-08-07 01:35:45,015 - /home/tools/HyLight/script/HyLight.py[line:132] - INFO: assemble long reads with clean graph
  ```
Thank again for your help,
Carole

**Comment by kangxiongbin** [comment]
Could you check if you have installed racon? The report indicates that the Racon software wasn't successfully installed. I recommend using conda to install Racon; it's quick and efficient.

Best,
Xiongbin

**Comment by CaroleBelliardo** [comment]
Thank you again for your help. Some error message persist : ```You need to rerun polyte in /kwak/hub/25_cbelliardo/MISTIC/1_reads_rawdata/hybrid_assembly/salade_I__test_v3/tmp//fq_15000/99707/ or decrease the size of cluster and rerun the whole steps
Error executing the command: cat /kwak/hub/25_cbelliardo/MISTIC/1_reads_rawdata/hybrid_assembly/salade_I__test_v3/tmp//fq_15000/*/contigs.fasta > /kwak/hub/25_cbelliardo/MISTIC/1_reads_rawdata/hybrid_assembly/salade_I__test_v3/tmp//all.contigs_15000.fasta
cat: '/kwak/hub/25_cbelliardo/MISTIC/1_reads_rawdata/hybrid_assembly/salade_I__test_v3/tmp//fq_15000/*/contigs.fasta': No such file or directory
``` but 'long_con_polished.fa' is not empty anymore.

**Comment by kangxiongbin** [comment]
Was the file final_contigs.fa generated in the end? If so, the error is likely due to failed assembly of short reads in some small groups. In small groups, it's common for assembly to fail if the read coverage is too low. This is a normal occurrence. final_contigs.fa is your final assembly result.

**Comment by Hedi65** [comment]
Thanks for the useful information 

I have the same issue. After waiting for almost 20 hours, I got the  following error 

cat: /media/biostud-bioinf-group/98bbc3e4-c1e9-4578-a451-b1129e9845ff/media/test_R/Hylight_res/tmp//cmd_polyte.sh: No such file or directory
Error executing the command: cat /media/biostud-bioinf-group/98bbc3e4-c1e9-4578-a451-b1129e9845ff/media/test_R/Hylight_res/tmp//fq_15000/*/contigs.fasta > /media/biostud-bioinf-group/98bbc3e4-c1e9-4578-a451-b1129e9845ff/media/test_R/Hylight_res/tmp//all.contigs_15000.fasta
cat: '/media/biostud-bioinf-group/98bbc3e4-c1e9-4578-a451-b1129e9845ff/media/test_R/Hylight_res/tmp//fq_15000/*/contigs.fasta': No such file or directory


My installation was through Conda. in my case, final_contigs.fa was not created. both output.txt and long_con_polished.fa is empty. how should we deal with this error?

Thanks
